#!/usr/bin/env python3
"""Render a human queue view from one batch translation manifest."""

from __future__ import annotations

import argparse
import json
import tempfile
from collections import Counter
from pathlib import Path


ITEM_STATES = {"ready", "in_progress", "done", "needs_fix"}
MECHANICAL_STATES = {"pending", "passed", "failed"}
REVIEW_STATES = {"pending", "passed", "needs_fix"}
SEMANTIC_STATES = {"pending", "clean", "warnings", "needs_fix"}
REQUIRED_ITEM_KEYS = {
    "id",
    "source",
    "output",
    "status",
    "mechanical_check",
    "content_coverage",
    "semantic_check",
    "expression_quality",
    "warnings",
    "updated_at",
}


def check_review(value: object, label: str, item_id: str) -> None:
    if not isinstance(value, dict) or set(value) != {"status", "note"}:
        raise ValueError(f"manifest item {item_id} has an invalid {label} record")
    if value["status"] not in REVIEW_STATES or not isinstance(value["note"], str):
        raise ValueError(f"manifest item {item_id} has invalid {label} values")


def load_manifest(path: Path) -> list[dict[str, object]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict) or payload.get("schema_version") != 3 or not isinstance(payload.get("items"), list):
        raise ValueError("manifest must use batch schema_version 3 with an items list")

    items = payload["items"]
    assert isinstance(items, list)
    seen: set[str] = set()
    for item in items:
        if not isinstance(item, dict) or set(item) != REQUIRED_ITEM_KEYS:
            raise ValueError("each manifest item must contain the documented batch fields")
        item_id = item["id"]
        if not isinstance(item_id, str) or not item_id or item_id in seen:
            raise ValueError("manifest item ids must be unique non-empty strings")
        seen.add(item_id)
        if not all(isinstance(item[key], str) and item[key] for key in ("source", "output", "updated_at")):
            raise ValueError(f"manifest item {item_id} needs source, output, and updated_at")
        if item["status"] not in ITEM_STATES:
            raise ValueError(f"manifest item {item_id} has an invalid status")
        mechanical = item["mechanical_check"]
        if not isinstance(mechanical, dict) or set(mechanical) != {"structure", "resources"}:
            raise ValueError(f"manifest item {item_id} has an invalid mechanical_check record")
        if any(value not in MECHANICAL_STATES for value in mechanical.values()):
            raise ValueError(f"manifest item {item_id} has invalid mechanical check values")
        check_review(item["content_coverage"], "content_coverage", item_id)
        check_review(item["expression_quality"], "expression_quality", item_id)
        semantic = item["semantic_check"]
        if not isinstance(semantic, dict) or set(semantic) != {"status", "report", "warning_codes", "warning_count"}:
            raise ValueError(f"manifest item {item_id} has an invalid semantic_check record")
        if semantic["status"] not in SEMANTIC_STATES or not isinstance(semantic["report"], str):
            raise ValueError(f"manifest item {item_id} has invalid semantic values")
        if not isinstance(semantic["warning_codes"], list) or not all(isinstance(code, str) for code in semantic["warning_codes"]):
            raise ValueError(f"manifest item {item_id} has invalid semantic warning codes")
        if not isinstance(semantic["warning_count"], int) or semantic["warning_count"] < 0:
            raise ValueError(f"manifest item {item_id} has an invalid semantic warning count")
        if not isinstance(item["warnings"], list) or not all(isinstance(warning, str) for warning in item["warnings"]):
            raise ValueError(f"manifest item {item_id} has invalid warnings")
    return items


def render_queue(items: list[dict[str, object]]) -> str:
    states = Counter(str(item["status"]) for item in items)
    high_risk = [item for item in items if int(item["semantic_check"]["warning_count"]) >= 10]  # type: ignore[index]
    lines = [
        "# Translation Queue",
        "",
        "Generated from the batch manifest. Do not edit this file directly.",
        "",
        f"Summary: total={len(items)} ready={states['ready']} in_progress={states['in_progress']} done={states['done']} needs_fix={states['needs_fix']} high_risk={len(high_risk)}",
        "",
        "## Items",
    ]
    for item in items:
        mechanical = item["mechanical_check"]
        semantic = item["semantic_check"]
        assert isinstance(mechanical, dict) and isinstance(semantic, dict)
        lines.append(
            f"- {item['id']} | status={item['status']} | structure={mechanical['structure']} | resources={mechanical['resources']} | "
            f"semantic={semantic['status']}({semantic['warning_count']}) | coverage={item['content_coverage']['status']} | "  # type: ignore[index]
            f"expression={item['expression_quality']['status']} | {item['output']}"  # type: ignore[index]
        )
    if high_risk:
        lines.extend(["", "## High Risk"])
        lines.extend(f"- {item['id']} | warnings={item['semantic_check']['warning_count']} | {item['output']}" for item in high_risk)  # type: ignore[index]
    return "\n".join(lines) + "\n"


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, prefix=f".{path.name}.", delete=False) as handle:
        handle.write(content)
        temporary = Path(handle.name)
    temporary.replace(path)


def sample_item(item_id: str, status: str = "done", warning_count: int = 12) -> dict[str, object]:
    return {
        "id": item_id,
        "source": f"articles/{item_id}/index.html",
        "output": f"derived/{item_id}/index.zh.html",
        "status": status,
        "mechanical_check": {"structure": "passed", "resources": "passed"},
        "content_coverage": {"status": "passed", "note": "sampled"},
        "semantic_check": {"status": "warnings", "report": f"reports/{item_id}.json", "warning_codes": ["long_english_unchanged"], "warning_count": warning_count},
        "expression_quality": {"status": "pending", "note": "not reviewed"},
        "warnings": ["quoted English retained"],
        "updated_at": "2026/07/17 12:00",
    }


def self_check() -> int:
    valid = {"schema_version": 3, "items": [sample_item("001"), sample_item("002", "needs_fix", 0)]}
    with tempfile.TemporaryDirectory() as temp:
        root = Path(temp)
        manifest = root / "manifest.json"
        output = root / "queue.md"
        manifest.write_text(json.dumps(valid), encoding="utf-8")
        items = load_manifest(manifest)
        atomic_write(output, render_queue(items))
        queue = output.read_text(encoding="utf-8")
        assert "high_risk=1" in queue and "status=needs_fix" in queue
        valid["items"].append(sample_item("001"))
        manifest.write_text(json.dumps(valid), encoding="utf-8")
        try:
            load_manifest(manifest)
        except ValueError as error:
            assert "unique" in str(error)
        else:
            raise AssertionError("duplicate manifest item id was accepted")
    print("self-check ok")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render a read-only queue view from a batch translation manifest.")
    parser.add_argument("--manifest", help="Batch schema v3 manifest.")
    parser.add_argument("--output", help="Generated queue.md path.")
    parser.add_argument("--self-check", action="store_true", help="Run built-in manifest and render checks.")
    args = parser.parse_args(argv)
    if args.self_check:
        return self_check()
    if not args.manifest or not args.output:
        parser.error("--manifest and --output are required unless --self-check is used")
    try:
        manifest = Path(args.manifest)
        output = Path(args.output)
        if manifest.resolve() == output.resolve():
            raise ValueError("queue output cannot replace the manifest")
        atomic_write(output, render_queue(load_manifest(manifest)))
    except (OSError, ValueError, json.JSONDecodeError) as error:
        parser.error(str(error))
    print(f"rendered queue -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
